# Generated by Django 5.1.3 on 2024-12-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0002_address_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.ManyToManyField(to='bookmodule.address'),
        ),
    ]
