# Generated by Django 5.1.6 on 2025-04-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0002_address2_gallery_student2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address2',
            name='street',
        ),
        migrations.RemoveField(
            model_name='student2',
            name='email',
        ),
        migrations.AddField(
            model_name='student2',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
