# Generated by Django 5.1.6 on 2025-04-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0003_remove_address2_street_remove_student2_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
